(ns h264.encode-p-slice-test
  "Tests for `h264.encode/encode-gop`'s P-slice (inter) encode support — the
   encode-side counterpart of `h264.decode/decode-gop`'s P_Skip/P_L0_16x16
   decode (ADR-2607122000 Migration step 7's encode increment). See
   `h264.encode`'s namespace docstring (\"P-slice (inter) encode\" section)
   for the exact scope: single reference frame (the immediately-preceding
   frame's OWN reconstruction), integer-pel full search (`me-full-search`,
   default ±8 px) + a small quarter-pel local refinement
   (`me-subpel-refine`, ±3 quarter-samples) motion estimation, P_Skip chosen
   whenever the §8.4.1.1 skip predictor already gives EXACT (zero-SAD)
   prediction, otherwise P_L0_16x16 with real (possibly sub-pel) motion and
   CAVLC-coded residual. NOT a claim of RDO-grade motion search — this is
   the \"簡易\" (simplified) search this task's own scope allows.

   Two kinds of test here, mirroring `h264.encode-test`'s own two-tier
   discipline:

   1. Round-trip through THIS REPO's own `h264.decode` (fast, no external
      tools needed) — a fresh 2-frame (IDR + P) GOP is encoded and decoded
      in-process for both cases the task requires:
      - Case A: two IDENTICAL flat frames → the encoder must choose P_Skip
        for every macroblock (flat content's IDR reconstruction is
        provably bit-exact at any QP — see `h264.encode-test`'s own
        `flat-multi-mb-roundtrip-bit-exact` — so the P_Skip predictor's
        zero-SAD condition is guaranteed to trigger), and the P-frame
        reconstructs BIT-EXACT to the source (P_Skip's whole point: no
        residual at all).
      - Case B: a real 2-D gradient IDR frame followed by a P-frame that's
        the SAME content genuinely translated (a real pixel-domain shift,
        not just re-evaluated per-frame noise) — the encoder must choose
        P_L0_16x16 with a REAL (nonzero) motion vector for at least one
        macroblock, and the reconstruction error against the (un-quantized)
        translated source stays small/bounded (real lossy inter coding,
        not a claim of exactness — the reference frame the encoder searches
        against is itself a lossy IDR reconstruction, so even a perfect
        motion match can't fully cancel the IDR's own quantization noise).
   2. Fixed fixtures (`p-slice-*.h264`), generated by `h264.encode/encode-gop`
      ONCE (see each fixture's own test docstring for the exact generation
      recipe) and independently verified at development time (2026-07,
      ffmpeg 8.1.1) to be decoded BIT-EXACT by REAL ffmpeg — same
      \"golden vector, ffmpeg-validated\" discipline every other
      encode/decode fixture in this repo uses:
        ffmpeg -v error -i p-slice-skip-flat32.h264 -pix_fmt yuv420p out.yuv
        ffmpeg -v error -i p-slice-l0-16x16-shift32.h264 -pix_fmt yuv420p out.yuv
      Both produced `0 decode errors`, no `corrupted macroblock`/`error
      while decoding` messages, and the resulting `.ref.yuv` files (checked
      in alongside the `.h264` fixtures) are bit-exact against THIS repo's
      own `h264.decode/decode-gop` output for both frames, luma AND chroma —
      a genuine independent-decoder cross-check (ffmpeg never saw or
      trusted anything about how these bytes were constructed)."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.java.io :as io]
            [h264.encode :as encode]
            [h264.decode :as decode]))

(defn- rd [p] (mapv #(bit-and (int %) 0xff) (with-open [in (io/input-stream (io/resource p))] (.readAllBytes in))))

(defn- sad [a b] (reduce + (map (fn [x y] (let [d (- x y)] (if (neg? d) (- d) d))) a b)))

(defn- frame-planes
  "Split a flat yuv420p byte seq (possibly multiple concatenated frames)
   into {:luma :cb :cr} for ONE frame of `width`x`height`, starting at
   `offset` (bytes) — same helper `h264.decode-p-slice-test` uses."
  [yuv offset width height]
  (let [luma-size (* width height)
        chroma-size (* (quot width 2) (quot height 2))
        v (vec yuv)]
    {:luma (subvec v offset (+ offset luma-size))
     :cb (subvec v (+ offset luma-size) (+ offset luma-size chroma-size))
     :cr (subvec v (+ offset luma-size chroma-size) (+ offset luma-size (* 2 chroma-size)))}))

(defn- shift-right
  "Genuine pixel-domain horizontal translation (wraparound) of a flat
   row-major `grid` (`w`x`h`) by `dx` pixels — real motion, not re-evaluated
   per-frame noise."
  [grid w h dx]
  (vec (for [r (range h) c (range w)]
         (nth grid (+ (* r w) (mod (- c dx) w))))))

;; --- Case A: round-trip, two identical FLAT frames -> P_Skip everywhere ---

(deftest p-skip-flat-roundtrip-bit-exact
  (testing "two identical flat 32x32 frames: the P-frame encoder chooses
   P_Skip for every macroblock (flat content's IDR reconstruction is
   bit-exact at any QP, so the skip predictor's zero-SAD condition is
   guaranteed), and the P-frame round-trips bit-exact through our own
   decoder"
    (let [luma (vec (repeat 1024 120))
          {:keys [bytes]} (encode/encode-gop {:width 32 :height 32 :qp 26
                                               :frames [{:luma luma} {:luma luma}]})
          frames (decode/decode-gop bytes)]
      (is (= 2 (count frames)))
      (is (= :i (:slice-type-class (first frames))))
      (is (= :p (:slice-type-class (second frames))))
      (is (every? true? (:mb-inter? (second frames))) "every P-frame macroblock is inter-coded")
      (is (every? #(= [0 0] %) (:mb-mvs (second frames))) "every P-frame macroblock is P_Skip (MV=[0,0], the trivial skip predictor for un-neighbored/matching-neighbor content)")
      (is (= luma (:luma (second frames))) "P_Skip reconstructs the source bit-exact (no residual, by definition)")
      (is (= (:luma (first frames)) (:luma (second frames))) "frame 0 (IDR) and frame 1 (P) reconstruct identically"))))

;; --- Case B: round-trip, real gradient IDR + genuinely-translated P-frame
;;     -> real (nonzero) P_L0_16x16 motion, bounded reconstruction error ---

(deftest p-l0-16x16-real-motion-roundtrip-bounded-error
  (testing "a real 2-D gradient IDR frame followed by a genuinely
   translated (2px horizontal shift) P-frame: the encoder finds a REAL
   nonzero motion vector via full search + sub-pel refinement for at least
   one macroblock (not P_Skip — a 2px shift does not leave the skip
   predictor's zero-SAD condition satisfied against a lossy IDR
   reference), and the reconstruction error against the (lossless) shifted
   source stays small"
    (let [luma0 (vec (for [r (range 32) c (range 32)] (mod (+ (* r 4) (* c 6) 60) 180)))
          luma1 (shift-right luma0 32 32 2)
          {:keys [bytes]} (encode/encode-gop {:width 32 :height 32 :qp 24
                                               :frames [{:luma luma0} {:luma luma1}]})
          frames (decode/decode-gop bytes)]
      (is (= 2 (count frames)))
      (is (= :p (:slice-type-class (second frames))))
      (is (every? true? (:mb-inter? (second frames))) "every P-frame macroblock is inter-coded")
      (is (some (fn [mv] (not= [0 0] mv)) (:mb-mvs (second frames)))
          "at least one macroblock has a REAL nonzero motion vector (not degenerate to all-P_Skip)")
      (is (< (/ (double (sad luma1 (:luma (second frames)))) 1024.0) 3.0)
          "average per-pixel luma reconstruction error stays small against the true (lossless) translated source"))))

;; --- Fixed fixtures, ffmpeg-validated (see namespace docstring) ---

(deftest p-slice-skip-flat32-golden-vector
  (testing "p-slice-skip-flat32.h264 — generated by
   `(h264.encode/encode-gop {:width 32 :height 32 :qp 26 :frames [{:luma flat120} {:luma flat120}]})`
   (flat120 = 1024 pixels of value 120) and independently verified (2026-07,
   ffmpeg 8.1.1) to decode with 0 decode errors:
     ffmpeg -v error -i p-slice-skip-flat32.h264 -pix_fmt yuv420p out.yuv
   — producing exactly this fixture's `.ref.yuv` (2 concatenated I420
   frames, 32x32)."
    (let [bytes (rd "h264/fixtures/p-slice-skip-flat32.h264")
          frames (decode/decode-gop bytes)
          ref (rd "h264/fixtures/p-slice-skip-flat32.ref.yuv")
          frame-size (+ 1024 256 256)]
      (is (= 2 (count frames)))
      (is (= :i (:slice-type-class (first frames))))
      (is (= :p (:slice-type-class (second frames))))
      (is (every? true? (:mb-inter? (second frames))))
      (is (every? #(= [0 0] %) (:mb-mvs (second frames))))
      (doseq [[idx frame] (map-indexed vector frames)]
        (let [planes (frame-planes ref (* idx frame-size) 32 32)]
          (testing (str "frame " idx " reconstructed luma/Cb/Cr are bit-exact vs. real ffmpeg's INDEPENDENT decode of this exact file")
            (is (= (:luma planes) (:luma frame)))
            (is (= (:cb planes) (:cb frame)))
            (is (= (:cr planes) (:cr frame)))))))))

(deftest p-slice-l0-16x16-shift32-golden-vector
  (testing "p-slice-l0-16x16-shift32.h264 — generated by
   `(h264.encode/encode-gop {:width 32 :height 32 :qp 24 :frames [{:luma g} {:luma (shift-right g 32 32 2)}]})`
   (g a real 2-D `(mod (+ (* r 4) (* c 6) 60) 180)` gradient) and
   independently verified (2026-07, ffmpeg 8.1.1) to decode with 0 decode
   errors:
     ffmpeg -v error -i p-slice-l0-16x16-shift32.h264 -pix_fmt yuv420p out.yuv
   — producing exactly this fixture's `.ref.yuv` (2 concatenated I420
   frames, 32x32). This is the strongest interoperability evidence in this
   test suite: a real 2px translation, encoded by THIS repo's own
   motion-estimation search into a genuinely nonzero P_L0_16x16 motion
   vector plus real CAVLC-coded residual, decoded bit-exact by an
   INDEPENDENT real decoder that never saw or trusted anything about how
   these bytes were constructed."
    (let [bytes (rd "h264/fixtures/p-slice-l0-16x16-shift32.h264")
          frames (decode/decode-gop bytes)
          ref (rd "h264/fixtures/p-slice-l0-16x16-shift32.ref.yuv")
          frame-size (+ 1024 256 256)]
      (is (= 2 (count frames)))
      (is (= :i (:slice-type-class (first frames))))
      (is (= :p (:slice-type-class (second frames))))
      (is (every? true? (:mb-inter? (second frames))))
      (is (some (fn [mv] (not= [0 0] mv)) (:mb-mvs (second frames)))
          "a real nonzero motion vector was actually chosen, not degenerate to all-P_Skip")
      (doseq [[idx frame] (map-indexed vector frames)]
        (let [planes (frame-planes ref (* idx frame-size) 32 32)]
          (testing (str "frame " idx " reconstructed luma/Cb/Cr are bit-exact vs. real ffmpeg's INDEPENDENT decode of this exact file")
            (is (= (:luma planes) (:luma frame)))
            (is (= (:cb planes) (:cb frame)))
            (is (= (:cr planes) (:cr frame)))))))))
