(ns h264.encode-test
  "Tests for `h264.encode` (ADR-2607122000 Migration step 8: encode-side
   量子化→変換→CAVLC→簡易モード決定, luma-only Intra_16x16, see that
   namespace's docstring for full scope). Two kinds of test here:

   1. Round-trip through THIS REPO's own `h264.decode` (fast, runs in CI,
      no external tools needed) — verifies the encoder produces a
      self-consistent bitstream its own decoder can parse, with bounded
      reconstruction error.
   2. Fixed fixtures (`encode-*.h264`) generated by `h264.encode` ONCE and
      independently verified, at development time, to be decodable by REAL
      ffmpeg (8.1.1) BIT-EXACT against ffmpeg's own decode of the same
      file — see each fixture's test docstring for the exact verification
      command. Same \"golden vector, ffmpeg-validated\" discipline
      `h264.decode`'s own tests use, checking the OPPOSITE direction (our
      encode → real ffmpeg decode).

   Development-time note, kept for traceability rather than deleted: while
   building this encoder, two apparent decode-side gaps were hit (a
   macroblock referencing a neighbor with real AC content, and any single
   macroblock whose AC coefficients push the neighbor-derived nC to 2 or
   higher). Both turned out to be manifestations of the SAME two bugs
   `h264.decode`/`h264.transform` had JUST been fixed for upstream in this
   repo's own history (commit `14e72ea`, \"resolve luma Horizontal
   multi-macroblock CAVLC desync\": `blk->col-row` was a transposed/wrong
   block-index mapping, and `luma-dc-hadamard` was missing an internal
   transpose) — `h264.encode` was initially developed against a stale west
   pin predating that fix. After syncing to the fixed `h264.decode` (and
   fixing this encoder's OWN `dc-nc` derivation, which had the SAME
   `:dc-nnz`-vs-`:ac-nnz` bug the upstream fix corrected on the decode
   side — see `encode-macroblock!`'s `dc-nc` binding), ALL previously-
   failing cases — including the original complex multi-macroblock,
   real-AC, Horizontal-prediction test image — decode bit-exact via real
   ffmpeg. No known decode-side gap remains open as of this test suite."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.java.io :as io]
            [h264.encode :as encode]
            [h264.decode :as decode]))

(defn- rd [p] (mapv #(bit-and (int %) 0xff) (with-open [in (io/input-stream (io/resource p))] (.readAllBytes in))))

(defn- sad [a b] (reduce + (map (fn [x y] (let [d (- x y)] (if (neg? d) (- d) d))) a b)))

(deftest flat-single-mb-roundtrip-bit-exact
  (testing "a flat 16x16 macroblock round-trips bit-exact through our own decoder across a wide QP range (no AC residual is ever needed for a truly flat block, so this only exercises the DC path)"
    (doseq [qp [0 5 15 24 26 35 45 51]]
      (let [luma (vec (repeat 256 128))
            {:keys [bytes]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp qp :luma luma})
            result (decode/decode-idr-frame bytes)]
        (is (= luma (:luma result)) (str "qp=" qp))))))

(deftest flat-multi-mb-roundtrip-bit-exact
  (testing "a flat 32x32 (4 macroblock) picture round-trips bit-exact — exercises cross-macroblock DC-only prediction without needing AC"
    (let [luma (vec (repeat 1024 100))
          {:keys [bytes mb-states]} (encode/encode-idr-luma-frame {:width 32 :height 32 :qp 24 :luma luma})
          result (decode/decode-idr-frame bytes)]
      (is (= luma (:luma result)))
      (is (= 4 (count mb-states))))))

(deftest gradient-single-mb-roundtrip-bounded-error
  (testing "a single-macroblock horizontal gradient (real AC residual, CodedBlockPatternLuma=15) round-trips through our own decoder with small, bounded lossy-compression error"
    (let [luma (vec (for [_r (range 16) c (range 16)] (+ 100 (* c 2))))
          {:keys [bytes mb-states]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp 20 :luma luma})
          result (decode/decode-idr-frame bytes)]
      (is (some (fn [state] (some pos? (:ac-nnz state))) mb-states)
          "at least one AC block actually carries a nonzero coefficient (sanity: not silently degenerating to DC-only)")
      (is (< (sad luma (:luma result)) (* 256 3)) "average per-pixel error stays small (<3) at this QP"))))

(deftest gradient-multi-mb-roundtrip-bounded-error
  (testing "a 2x2-macroblock diagonal gradient (real AC + cross-macroblock neighbor derivation for both intra prediction and CAVLC nC, including the DC block's own nC) round-trips through our own decoder with bounded error"
    (let [luma (vec (for [r (range 32) c (range 32)] (mod (+ (* r 3) (* c 5) 50) 200)))
          {:keys [bytes mb-states]} (encode/encode-idr-luma-frame {:width 32 :height 32 :qp 24 :luma luma})
          result (decode/decode-idr-frame bytes)]
      (is (= 4 (count mb-states)))
      (is (< (/ (sad luma (:luma result)) 1024.0) 3.0) "average per-pixel error stays small"))))

(deftest mode-decision-chooses-among-available-modes
  (testing "mode decision picks DC for the first (no-neighbor) macroblock, and is free to pick DC/Vertical/Horizontal for later ones depending on which minimizes SAD"
    (let [luma (vec (repeat 256 128))
          {:keys [mb-states]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp 26 :luma luma})]
      (is (= 2 (:pred-mode (first mb-states))) "DC (mode 2) is the only legal choice with no neighbors"))))

(deftest cbp-luma-zero-for-flat-content
  (testing "CodedBlockPatternLuma degenerates to 0 (no AC blocks coded) for genuinely flat content, matching h264.decode/i16x16-mb-info's mb_type<=12 case"
    (let [luma (vec (repeat 256 128))
          {:keys [mb-states]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp 26 :luma luma})]
      (is (every? zero? (:ac-nnz (first mb-states)))))))

(deftest encode-mb0-realac-golden-vector
  (testing "encode-mb0-realac.h264 — a single Intra_16x16 macroblock with a real 16x16 horizontal gradient (100..130), giving REAL (nonzero) AC residual at QP 20, generated by `h264.encode`, and independently verified (2026-07, ffmpeg 8.1.1) to decode bit-exact via real ffmpeg:
       ffmpeg -i encode-mb0-realac.h264 -pix_fmt yuv420p out.yuv
     — producing exactly this fixture's `.ref.yuv`. Re-verifies the
     checked-in fixture decodes identically via THIS REPO's own decoder,
     demonstrating this encoder's output is a real, interoperable H.264
     Annex B bitstream."
    (let [bytes (rd "h264/fixtures/encode-mb0-realac.h264")
          ref (rd "h264/fixtures/encode-mb0-realac.ref.yuv")
          result (decode/decode-idr-frame bytes)
          luma-ref (vec (take 256 ref))]
      (is (= 16 (:width result)))
      (is (= 16 (:height result)))
      (is (= luma-ref (:luma result)) "bit-exact vs real ffmpeg's own decode of this exact file")
      (is (> (count (distinct (:luma result))) 1) "real AC content, not degenerate to flat"))))

(deftest encode-flat32-multimb-golden-vector
  (testing "encode-flat32-multimb.h264 — a 32x32 (2x2 macroblock) FLAT picture (CodedBlockPatternLuma=0 for all 4 MBs, exercising multi-macroblock DC/Vertical/Horizontal intra prediction chaining without AC residual), generated by `h264.encode` and independently verified (2026-07, ffmpeg 8.1.1) to decode bit-exact via real ffmpeg, reproducing the exact uniform source value (100) in every pixel."
    (let [bytes (rd "h264/fixtures/encode-flat32-multimb.h264")
          ref (rd "h264/fixtures/encode-flat32-multimb.ref.yuv")
          result (decode/decode-idr-frame bytes)
          luma-ref (vec (take 1024 ref))]
      (is (= 32 (:width result)))
      (is (= 32 (:height result)))
      (is (= luma-ref (:luma result)) "bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= [100] (distinct (:luma result)))))))

(deftest encode-multimb-realac-golden-vector
  (testing "encode-multimb-realac.h264 — a 32x32 (2x2 macroblock) picture with a real 2-D oscillating pattern (`sin`/`cos` of position, same style as this repo's own decode-side `chroma-multimb32.h264` fixture, but here applied to LUMA), giving REAL AC residual in EVERY macroblock plus real cross-macroblock CAVLC neighbor (nC) derivation for both AC blocks AND the Intra16x16 luma-DC block, and Horizontal Intra_16x16 prediction actually selected for 2 of the 4 macroblocks — generated by `h264.encode` at QP 24 and independently verified (2026-07, ffmpeg 8.1.1) to decode BIT-EXACT via real ffmpeg (zero pixel difference from ffmpeg's own decode of this exact file, and zero `corrupted macroblock`/`error while decoding` messages). This is the strongest interoperability evidence in this test suite — the exact combination (multi-MB + real AC + cross-MB nC + Horizontal prediction) that most exercises the encoder's quantizer, CAVLC writer, and neighbor bookkeeping together."
    (let [bytes (rd "h264/fixtures/encode-multimb-realac.h264")
          ref (rd "h264/fixtures/encode-multimb-realac.ref.yuv")
          result (decode/decode-idr-frame bytes)
          luma-ref (vec (take 1024 ref))]
      (is (= 32 (:width result)))
      (is (= 32 (:height result)))
      (is (= luma-ref (:luma result)) "bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= [2 1 0 0] (:mb-pred-modes result))
          "a real mix of prediction modes was actually selected (DC, Horizontal, Vertical), not a degenerate single mode")
      (is (> (count (distinct (:luma result))) 1) "real AC content, not degenerate to flat"))))

;; --- Chroma encode (chroma-encode follow-up to Migration step 8, see
;;     namespace docstring: real Cb/Cr DC+AC residual, DC/Horizontal/Vertical
;;     Intra_Chroma mode decision) ---

(deftest chroma-defaults-to-flat-when-omitted
  (testing "omitting :cb/:cr from encode-idr-luma-frame's input preserves this fn's ORIGINAL luma-only behavior exactly (flat 128 chroma planes, zero residual, CodedBlockPatternChroma degenerates to 0) — backward compatibility for existing callers that never passed chroma."
    (let [luma (vec (repeat 256 128))
          {:keys [mb-states]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp 20 :luma luma})]
      (is (= 0 (:intra-chroma-pred-mode (first mb-states))))
      (is (every? zero? (:ac-nnz (:cb (first mb-states)))))
      (is (every? zero? (:ac-nnz (:cr (first mb-states)))))
      (is (= [128] (distinct (apply concat (:recon (:cb (first mb-states))))))))))

(deftest chroma-single-mb-roundtrip-bounded-error
  (testing "a single-macroblock real Cb/Cr gradient (distinct per-component content, real AC residual) round-trips through our own decoder with small bounded error, and picks a legal chroma mode"
    (let [luma (vec (repeat 256 128))
          cb (vec (for [_r (range 8) c (range 8)] (+ 80 (* c 6))))
          cr (vec (for [r (range 8) _c (range 8)] (+ 160 (* r 6))))
          {:keys [bytes mb-states]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp 20 :luma luma :cb cb :cr cr})
          result (decode/decode-idr-frame bytes)]
      (is (some pos? (:ac-nnz (:cb (first mb-states)))) "Cb actually carries real AC residual, not degenerate to DC-only")
      (is (some pos? (:ac-nnz (:cr (first mb-states)))) "Cr actually carries real AC residual, not degenerate to DC-only")
      (is (< (sad cb (:cb result)) (* 64 3)) "Cb average per-pixel error stays small at this QP")
      (is (< (sad cr (:cr result)) (* 64 3)) "Cr average per-pixel error stays small at this QP"))))

(deftest chroma-multimb-realac-roundtrip-bounded-error
  (testing "a 32x32 (2x2-macroblock) picture with a real 2-D oscillating Cb/Cr pattern (flat luma, so libx264-style RD reasoning would keep luma Intra_16x16 DC-only — mirrors this repo's own decode-side chroma-multimb32.h264 fixture's design) round-trips through our own decoder with bounded error, exercising real cross-macroblock chroma AC CAVLC neighbor derivation for all 4 macroblocks and more than one Intra_Chroma prediction mode"
    (let [luma (vec (repeat 1024 128))
          cb (vec (for [r (range 16) c (range 16)] (int (+ 128 (* 40 (Math/sin (/ c 2.0)) (Math/cos (/ r 3.0)))))))
          cr (vec (for [r (range 16) c (range 16)] (int (+ 128 (* 40 (Math/cos (/ c 3.0)) (Math/sin (/ r 2.0)))))))
          {:keys [bytes mb-states]} (encode/encode-idr-luma-frame {:width 32 :height 32 :qp 20 :luma luma :cb cb :cr cr})
          result (decode/decode-idr-frame bytes)]
      (is (every? (fn [s] (some pos? (:ac-nnz (:cb s)))) mb-states) "every macroblock's Cb carries real AC residual")
      (is (every? (fn [s] (some pos? (:ac-nnz (:cr s)))) mb-states) "every macroblock's Cr carries real AC residual")
      (is (> (count (distinct (map :intra-chroma-pred-mode mb-states))) 1)
          "more than one Intra_Chroma mode was actually selected across these 4 macroblocks")
      (is (< (/ (sad cb (:cb result)) 256.0) 3.0) "Cb average per-pixel error stays small")
      (is (< (/ (sad cr (:cr result)) 256.0) 3.0) "Cr average per-pixel error stays small"))))

(deftest chroma-cbp-degenerates-to-zero-for-flat-content
  (testing "CodedBlockPatternChroma degenerates to 0 (no chroma residual at all) for genuinely flat 128 Cb/Cr content, matching h264.decode/i16x16-mb-info's mb_type formula's (m quot 4) mod 3 = 0 case"
    (let [luma (vec (repeat 256 128))
          cb (vec (repeat 64 128))
          cr (vec (repeat 64 128))
          {:keys [mb-states]} (encode/encode-idr-luma-frame {:width 16 :height 16 :qp 26 :luma luma :cb cb :cr cr})]
      (is (every? zero? (:ac-nnz (:cb (first mb-states)))))
      (is (every? zero? (:ac-nnz (:cr (first mb-states))))))))

(deftest encode-mb0-chroma-realac-golden-vector
  (testing "encode-mb0-chroma-realac.h264 — a single Intra_16x16 macroblock with a real 16x16 luma horizontal gradient (real luma AC) AND real, DISTINCT per-component 8x8 Cb/Cr gradients (Cb varies by column, Cr by row — so the two components are NOT the same content, cross-checking that Cb/Cr aren't accidentally swapped), giving real chroma AC residual (CodedBlockPatternChroma=2), generated by `h264.encode` at QP 20 and independently verified (2026-07, ffmpeg 8.1.1) to decode bit-exact via real ffmpeg:
       ffmpeg -i encode-mb0-chroma-realac.h264 -pix_fmt yuv420p out.yuv
     — producing exactly this fixture's `.ref.yuv` (luma+Cb+Cr, I420 layout)."
    (let [bytes (rd "h264/fixtures/encode-mb0-chroma-realac.h264")
          ref (rd "h264/fixtures/encode-mb0-chroma-realac.ref.yuv")
          result (decode/decode-idr-frame bytes)
          luma-ref (vec (take 256 ref))
          cb-ref (vec (subvec (vec ref) 256 320))
          cr-ref (vec (subvec (vec ref) 320 384))]
      (is (= 16 (:width result)))
      (is (= 16 (:height result)))
      (is (= luma-ref (:luma result)) "luma bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= cb-ref (:cb result)) "Cb bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= cr-ref (:cr result)) "Cr bit-exact vs real ffmpeg's own decode of this exact file")
      (is (> (count (distinct (:cb result))) 1) "real Cb AC content, not degenerate to flat")
      (is (> (count (distinct (:cr result))) 1) "real Cr AC content, not degenerate to flat")
      (is (not= (:cb result) (:cr result)) "Cb and Cr are genuinely different (not accidentally swapped/duplicated)"))))

(deftest encode-multimb-chroma-realac-golden-vector
  (testing "encode-multimb-chroma-realac.h264 — a 32x32 (2x2 macroblock) picture, flat luma but a real 2-D oscillating (sin/cos) Cb/Cr pattern (same style as this repo's decode-side chroma-multimb32.h264 fixture, but generated by THIS repo's OWN encoder rather than libx264), giving real chroma DC AND AC residual across all 4 macroblocks plus real cross-macroblock CAVLC neighbor (nC) derivation for chroma AC, and 3 distinct Intra_Chroma modes actually selected ([0 1 2 0] — DC/Horizontal/Vertical/DC) — generated by `h264.encode` at QP 20 and independently verified (2026-07, ffmpeg 8.1.1) to decode BIT-EXACT via real ffmpeg (zero pixel difference, zero `corrupted macroblock`/`error while decoding` messages). This is the strongest chroma-encode interoperability evidence in this test suite — multi-MB + real chroma AC + cross-MB chroma nC + multiple Intra_Chroma modes, all together."
    (let [bytes (rd "h264/fixtures/encode-multimb-chroma-realac.h264")
          ref (rd "h264/fixtures/encode-multimb-chroma-realac.ref.yuv")
          result (decode/decode-idr-frame bytes)
          luma-ref (vec (take 1024 ref))
          cb-ref (vec (subvec (vec ref) 1024 1280))
          cr-ref (vec (subvec (vec ref) 1280 1536))]
      (is (= 32 (:width result)))
      (is (= 32 (:height result)))
      (is (= luma-ref (:luma result)) "luma bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= cb-ref (:cb result)) "Cb bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= cr-ref (:cr result)) "Cr bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= [0 1 2 0] (:mb-intra-chroma-pred-modes result))
          "a real mix of Intra_Chroma modes was actually selected (DC, Horizontal, Vertical), not a degenerate single mode")
      (is (> (count (distinct (:cb result))) 1) "real Cb AC content, not degenerate to flat")
      (is (> (count (distinct (:cr result))) 1) "real Cr AC content, not degenerate to flat"))))

(deftest encode-multimb-chroma-dconly-golden-vector
  (testing "encode-multimb-chroma-dconly.h264 — a 32x32 (2x2 macroblock) picture, flat luma AND flat-but-nonzero Cb=150/Cr=180 chroma (no chroma AC anywhere — exercises CodedBlockPatternChroma=1 [DC only] for the first macroblock, whose default-128 no-neighbor DC prediction leaves a real nonzero DC residual, degenerating to CodedBlockPatternChroma=0 for later macroblocks whose neighbor-derived DC prediction already matches), generated by `h264.encode` at QP 20 and independently verified (2026-07, ffmpeg 8.1.1) to decode bit-exact via real ffmpeg, reproducing the exact uniform Cb/Cr source values in every pixel."
    (let [bytes (rd "h264/fixtures/encode-multimb-chroma-dconly.h264")
          ref (rd "h264/fixtures/encode-multimb-chroma-dconly.ref.yuv")
          result (decode/decode-idr-frame bytes)
          luma-ref (vec (take 1024 ref))
          cb-ref (vec (subvec (vec ref) 1024 1280))
          cr-ref (vec (subvec (vec ref) 1280 1536))]
      (is (= 32 (:width result)))
      (is (= 32 (:height result)))
      (is (= luma-ref (:luma result)) "luma bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= cb-ref (:cb result)) "Cb bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= cr-ref (:cr result)) "Cr bit-exact vs real ffmpeg's own decode of this exact file")
      (is (= [150] (distinct (:cb result))) "Cb reproduces the exact uniform source value, no chroma AC needed")
      (is (= [180] (distinct (:cr result))) "Cr reproduces the exact uniform source value, no chroma AC needed"))))
