(ns h264.sps-test
  "Validated against a real libx264-encoded (baseline profile) Annex B
   elementary stream generated by `ffmpeg -f lavfi -i testsrc=size=64x48
   ... -profile:v baseline -bsf:v h264_mp4toannexb`. `ffprobe` confirms the
   source is 64x48; this test asserts the SPS-derived dimensions match."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.java.io :as io]
            [h264.bitstream :as bs]
            [h264.rbsp :as rbsp]
            [h264.sps :as sps]))

(defn- rd [p] (mapv #(bit-and (int %) 0xff)
                    (with-open [in (io/input-stream (io/resource p))] (.readAllBytes in))))

(deftest sps-from-real-encoder
  (let [b     (rd "h264/fixtures/sample.h264")
        units (bs/nal-units b)
        sps-u (first (filter #(= :sps (:kind %)) units))]
    (testing "SPS NAL found"
      (is (some? sps-u)))
    (let [parsed (sps/parse (rbsp/unescape (:bytes sps-u)))]
      (testing "dimensions match the real 64x48 encode source"
        (is (= 64 (:width parsed)))
        (is (= 48 (:height parsed))))
      (testing "baseline profile (66), no scaling lists"
        (is (= 66 (:profile-idc parsed)))))))
